DEFAULT_TIMEZONE = "Asia/Shanghai"
PRESET_FALLBACK_INTERVALS = [360, 720, 1440, 4320]

WATCH_STATUS_PENDING = "pending"
SUBSCRIPTION_STATUS_PENDING = "pending"
SUBSCRIPTION_STATUS_SUBSCRIBED = "subscribed"
SYNC_STATUS_NEVER = "never"
